-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 09:44:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fitness_life
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fitness_life` ;

-- -----------------------------------------------------
-- Schema fitness_life
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness_life` DEFAULT CHARACTER SET utf8 ;
USE `fitness_life` ;

-- -----------------------------------------------------
-- Table `fitness_life`.`tb_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_pessoa` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_pessoa` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`perfil` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`perfil` (
  `idperfil` INT(4) NOT NULL,
  `perfil` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`usuario` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`usuario` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `perfil_idperfil` INT(4) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_pessoa_cpf`, `perfil_idperfil`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_tb_login_tb_pessoa`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `fitness_life`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_funcionario` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_funcionario` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `matricula` INT(5) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_pessoa_cpf`, `matricula`),
  CONSTRAINT `fk_tb_funcionario_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_aluno` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_aluno` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `data_entrada` DATE NOT NULL,
  `foto` BLOB NOT NULL,
  PRIMARY KEY (`id_pessoa_cpf`),
  CONSTRAINT `fk_tb_aluno_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_sala` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_sala` (
  `id_sala` INT(4) NOT NULL AUTO_INCREMENT,
  `localizacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_aula` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_aula` (
  `id_aula` INT(4) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_turma` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_turma` (
  `idtb_turma` INT NOT NULL,
  PRIMARY KEY (`idtb_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_turma_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_turma_aluno` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_turma_aluno` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `id_turma` INT(4) NOT NULL,
  PRIMARY KEY (`id_pessoa_cpf`, `id_turma`),
  INDEX `fk_tb_agenda_semanal_has_tb_aluno_tb_aluno1_idx` (`id_pessoa_cpf` ASC),
  INDEX `fk_tb_agenda_semanal_has_tb_aluno_tb_agenda_semanal1_idx` (`id_turma` ASC),
  CONSTRAINT `fk_tb_agenda_semanal_has_tb_aluno_tb_agenda_semanal1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `fitness_life`.`tb_turma` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agenda_semanal_has_tb_aluno_tb_aluno1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_aluno` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_turma` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_turma` (
  `idtb_turma` INT NOT NULL,
  PRIMARY KEY (`idtb_turma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_professor` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_professor` (
  `tb_funcionario_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`tb_funcionario_id_pessoa_cpf`),
  INDEX `fk_tb_professor_tb_funcionario1_idx` (`tb_funcionario_id_pessoa_cpf` ASC),
  CONSTRAINT `fk_tb_professor_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_funcionario` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_professor_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_professor_curso` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_professor_curso` (
  `tb_professor_tb_funcionario_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `curso` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`tb_professor_tb_funcionario_id_pessoa_cpf`),
  CONSTRAINT `fk_tb_professor_curso_tb_professor1`
    FOREIGN KEY (`tb_professor_tb_funcionario_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_professor` (`tb_funcionario_id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_pessoa_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_pessoa_telefone` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_pessoa_telefone` (
  `tb_pessoa_cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(18) NOT NULL,
  INDEX `fk_tb_pessoa_telefone_tb_pessoa1_idx` (`tb_pessoa_cpf` ASC),
  PRIMARY KEY (`tb_pessoa_cpf`, `telefone`),
  CONSTRAINT `fk_tb_pessoa_telefone_tb_pessoa1`
    FOREIGN KEY (`tb_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_peso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_peso` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_peso` (
  `tb_aluno_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `data` DATE NOT NULL,
  `peso` INT(3) NOT NULL,
  PRIMARY KEY (`data`, `tb_aluno_id_pessoa_cpf`),
  INDEX `fk_tb_peso_tb_aluno1_idx` (`tb_aluno_id_pessoa_cpf` ASC),
  CONSTRAINT `fk_tb_peso_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_aluno` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_pagamento` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_pagamento` (
  `tb_aluno_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `status` ENUM('Em aberto', 'Pago', 'Vencido') NOT NULL DEFAULT 'Em aberto',
  `boleto` LONGBLOB NOT NULL,
  `valor` INT(3) NOT NULL DEFAULT 100,
  PRIMARY KEY (`data_emissao`, `tb_aluno_id_pessoa_cpf`),
  INDEX `fk_tb_pagamento_tb_aluno1_idx` (`tb_aluno_id_pessoa_cpf` ASC),
  CONSTRAINT `fk_tb_pagamento_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_aluno` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_turma_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_turma_professor` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_turma_professor` (
  `tb_turma_id_codigo` INT(4) NOT NULL,
  `tb_professor_tb_funcionario_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`tb_turma_id_codigo`, `tb_professor_tb_funcionario_id_pessoa_cpf`),
  INDEX `fk_tb_turma_professor_tb_professor1_idx` (`tb_professor_tb_funcionario_id_pessoa_cpf` ASC),
  CONSTRAINT `fk_tb_turma_professor_tb_turma1`
    FOREIGN KEY (`tb_turma_id_codigo`)
    REFERENCES `fitness_life`.`tb_turma` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_turma_professor_tb_professor1`
    FOREIGN KEY (`tb_professor_tb_funcionario_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_professor` (`tb_funcionario_id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `fitness_life` ;

-- -----------------------------------------------------
-- Placeholder table for view `fitness_life`.`lista_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fitness_life`.`lista_turma` (`dia_da_semana` INT, `horario_inicial` INT, `horario_final` INT, `nome` INT, `localizacao` INT);

-- -----------------------------------------------------
-- View `fitness_life`.`lista_turma`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `fitness_life`.`lista_turma` ;
DROP TABLE IF EXISTS `fitness_life`.`lista_turma`;
USE `fitness_life`;
CREATE  OR REPLACE VIEW `lista_turma` AS SELECT t.dia_da_semana, t.horario_inicial, t.horario_final, a.nome, s.localizacao, ps.nome
FROM tb_turma AS t, tb_sala AS s, tb_aula AS a, tb_turma_professor AS tp, tb_pessoa AS ps
WHERE t.tb_sala_id_sala = s.id_sala AND t.aula_id_aula = a.id_aula AND t.id_codigo = tp.tb_turma_id_codigo AND ps.cpf = tp.tb_professor_tb_funcionario_id_pessoa_cpf;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
