-- MySQL Script generated by MySQL Workbench
-- Sun Jun 30 20:38:19 2019
-- Model: db_studiotopfit    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_studiotopfit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_studiotopfit` ;

-- -----------------------------------------------------
-- Schema db_studiotopfit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_studiotopfit` DEFAULT CHARACTER SET utf8 ;
USE `db_studiotopfit` ;

-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_pessoa` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_pessoa` (
  `cpf` BIGINT(11) NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`perfil` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`perfil` (
  `idperfil` INT(4) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`usuario` (
  `id_pessoa_cpf` BIGINT(11) NOT NULL,
  `perfil_idperfil` INT(4) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`perfil_idperfil`, `id_pessoa_cpf`),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC) ,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) ,
  CONSTRAINT `fk_tb_login_tb_pessoa`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `db_studiotopfit`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `db_studiotopfit`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_funcionario` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_funcionario` (
  `id_matricula` INT(9) NOT NULL,
  `id_pessoa_cpf` BIGINT(11) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  INDEX `fk_tb_funcionario_tb_pessoa1_idx` (`id_pessoa_cpf` ASC) ,
  PRIMARY KEY (`id_matricula`),
  CONSTRAINT `fk_tb_funcionario_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `db_studiotopfit`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_aluno` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_aluno` (
  `id_matricula` INT(9) NOT NULL,
  `id_pessoa_cpf` BIGINT(11) NOT NULL,
  `data_entrada` DATE NOT NULL,
  `foto` BLOB NOT NULL,
  PRIMARY KEY (`id_matricula`),
  CONSTRAINT `fk_tb_aluno_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `db_studiotopfit`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_local` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_local` (
  `id_local` INT(4) NOT NULL AUTO_INCREMENT,
  `localizacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_local`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_aula` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_aula` (
  `id_aula` INT(4) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_sala` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_sala` (
  `id_sala` INT(4) NOT NULL AUTO_INCREMENT,
  `localizacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_turma` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_turma` (
  `id_codigo` INT(4) NOT NULL,
  `tb_sala_id_sala` INT(4) NOT NULL,
  `aula_id_aula` INT(4) NOT NULL,
  `dia_da_semana` INT(1) NOT NULL,
  `horario_inicial` TIME NOT NULL,
  `horario_final` TIME NOT NULL, 
  `descricao` VARCHAR(250),
  `qtdMax` INT(3) NOT NULL,
  PRIMARY KEY (`id_codigo`),
  INDEX `fk_tb_turma_tb_sala_id_sala_turma` (`tb_sala_id_sala` ASC),
  INDEX `fk_tb_turma_aula_id_aula` (`aula_id_aula` ASC),
  CONSTRAINT `fk_tb_turma_tb_sala_id_sala_turma`
	FOREIGN KEY (`tb_sala_id_sala`) 
	REFERENCES `db_studiotopfit`.`tb_sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_turma_aula_id_aula`
	FOREIGN KEY (`aula_id_aula`) 
	REFERENCES `db_studiotopfit`.`tb_aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_professor` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_professor` (
  `tb_funcionario_id_matricula` INT(9) NOT NULL,
  PRIMARY KEY (`tb_funcionario_id_matricula`),
  CONSTRAINT `fk_tb_professor_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_id_matricula`)
    REFERENCES `db_studiotopfit`.`tb_funcionario` (`id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_curso` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_curso` (
  `curso` VARCHAR(40) NOT NULL,
  `tb_professor_tb_funcionario_id_matricula` INT(9) NOT NULL,
  PRIMARY KEY (`curso`, `tb_professor_tb_funcionario_id_matricula`),
  INDEX `fk_tb_curso_tb_professor1_idx` (`tb_professor_tb_funcionario_id_matricula` ASC) ,
  CONSTRAINT `fk_tb_curso_tb_professor1`
    FOREIGN KEY (`tb_professor_tb_funcionario_id_matricula`)
    REFERENCES `db_studiotopfit`.`tb_professor` (`tb_funcionario_id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_pessoa_telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_pessoa_telefone` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_pessoa_telefone` (
  `tb_pessoa_cpf` BIGINT(11) NOT NULL,
  `telefone` VARCHAR(18) NOT NULL,
  INDEX `fk_tb_pessoa_telefone_tb_pessoa1_idx` (`tb_pessoa_cpf` ASC) ,
  PRIMARY KEY (`tb_pessoa_cpf`, `telefone`),
  CONSTRAINT `fk_tb_pessoa_telefone_tb_pessoa1`
    FOREIGN KEY (`tb_pessoa_cpf`)
    REFERENCES `db_studiotopfit`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_pagamento` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_pagamento` (
  `id_data_emissao` DATE NOT NULL,
  `id_matricula` INT(6) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `status` ENUM('Em aberto', 'Pago', 'Vencido') NOT NULL DEFAULT 'Em aberto',
  `boleto` LONGBLOB NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL DEFAULT 100,
  PRIMARY KEY (`id_data_emissao`, `id_matricula`),
  INDEX `fk_tb_pagamento_tb_aluno1_idx` (`id_matricula` ASC) ,
  CONSTRAINT `fk_tb_pagamento_tb_aluno1`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `db_studiotopfit`.`tb_aluno` (`id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_turma_has_tb_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_turma_has_tb_professor` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_turma_has_tb_professor` (
  `tb_turma_id_codigo` INT NOT NULL,
  `tb_professor_tb_funcionario_id_matricula` INT(9) NOT NULL,
  PRIMARY KEY (`tb_turma_id_codigo`, `tb_professor_tb_funcionario_id_matricula`),
  INDEX `fk_tb_turma_has_tb_professor_tb_professor1` (`tb_professor_tb_funcionario_id_matricula` ASC) ,
  INDEX `fk_tb_turma_has_tb_professor_tb_turma1` (`tb_turma_id_codigo` ASC) ,
  CONSTRAINT `fk_tb_turma_has_tb_professor_tb_turma1`
    FOREIGN KEY (`tb_turma_id_codigo`)
    REFERENCES `db_studiotopfit`.`tb_turma` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_turma_has_tb_professor_tb_professor1`
    FOREIGN KEY (`tb_professor_tb_funcionario_id_matricula`)
    REFERENCES `db_studiotopfit`.`tb_professor` (`tb_funcionario_id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_studiotopfit`.`tb_turma_has_tb_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_studiotopfit`.`tb_turma_has_tb_aluno` ;

CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`tb_turma_has_tb_aluno` (
  `tb_turma_id_codigo` INT NOT NULL,
  `tb_aluno_id_matricula` INT(9) NOT NULL,
  PRIMARY KEY (`tb_turma_id_codigo`, `tb_aluno_id_matricula`),
  INDEX `fk_tb_turma_has_tb_aluno_tb_aluno1` (`tb_aluno_id_matricula` ASC) ,
  INDEX `fk_tb_turma_has_tb_aluno_tb_turma1` (`tb_turma_id_codigo` ASC) ,
  CONSTRAINT `fk_tb_turma_has_tb_aluno_tb_turma1`
    FOREIGN KEY (`tb_turma_id_codigo`)
    REFERENCES `db_studiotopfit`.`tb_turma` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_turma_has_tb_aluno_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_matricula`)
    REFERENCES `db_studiotopfit`.`tb_aluno` (`id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `db_studiotopfit` ;

-- -----------------------------------------------------
-- Placeholder table for view `db_studiotopfit`.`lista_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_studiotopfit`.`lista_turma` (`dia_da_semana` INT, `horario_inicial` INT, `horario_final` INT, `nome` INT, `localizacao` INT);

-- -----------------------------------------------------
-- View `db_studiotopfit`.`lista_turma`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `db_studiotopfit`.`lista_turma`;
-- DROP VIEW IF EXISTS `db_studiotopfit`.`lista_turma` ;
-- USE `db_studiotopfit`;
-- CREATE  OR REPLACE VIEW `lista_turma` AS SELECT t.dia_da_semana, t.horario_inicial, t.horario_final, a.nome, s.localizacao, ps.nome
-- FROM tb_turma AS t, tb_sala AS s, tb_aula AS a, tb_turma_professor AS tp, tb_pessoa AS ps
-- WHERE t.tb_sala_id_sala = s.id_sala AND t.aula_id_aula = a.id_aula AND t.id_codigo = tp.tb_turma_id_codigo AND ps.cpf = tp.tb_professor_tb_funcionario_id_pessoa_cpf;

-- -----------------------------------------------------
-- INSERT ADMIN LOGIN
-- -----------------------------------------------------
INSERT INTO perfil (idperfil, perfil) VALUES (3, 'Administrador');
INSERT INTO tb_pessoa (cpf, nome, sobrenome, sexo, data_nascimento, endereco, uf, cidade, bairro, rg, email) VALUES ('11111111111', 'admin', 'admin', '0', '1999-01-01', '', 'DF', 'Brasília', '', '', 'admin@admin.com');
INSERT INTO usuario (id_pessoa_cpf, perfil_idperfil, senha, usuario) VALUES ('11111111111', 3, '25f9e794323b453885f5181f1b624d0b', 'admin');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;