-- MySQL Script generated by MySQL Workbench
-- Fri Jul  5 05:52:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fitness_life
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fitness_life` ;

-- -----------------------------------------------------
-- Schema fitness_life
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fitness_life` DEFAULT CHARACTER SET latin1 ;
USE `fitness_life` ;

-- -----------------------------------------------------
-- Table `fitness_life`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`perfil` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`perfil` (
  `idperfil` INT(4) NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_aula` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_aula` (
  `id_aula` INT(4) NOT NULL,
  `nome_aula` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_sala` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_sala` (
  `id_sala` INT(4) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_agenda_semanal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_agenda_semanal` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_agenda_semanal` (
  `id_agenda_semanal` INT(4) NOT NULL AUTO_INCREMENT,
  `dia_da_semana` VARCHAR(15) NOT NULL,
  `horario_inicial` TIME NOT NULL,
  `horario_final` TIME NOT NULL,
  `tb_aula_id_aula` INT(4) NOT NULL,
  `tb_sala_id_sala` INT(4) NOT NULL,
  PRIMARY KEY (`id_agenda_semanal`),
  INDEX `fk_tb_agenda_semanal_tb_aula1_idx` (`tb_aula_id_aula` ASC) ,
  INDEX `fk_tb_agenda_semanal_tb_sala1_idx` (`tb_sala_id_sala` ASC) ,
  CONSTRAINT `fk_tb_agenda_semanal_tb_aula1`
    FOREIGN KEY (`tb_aula_id_aula`)
    REFERENCES `fitness_life`.`tb_aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agenda_semanal_tb_sala1`
    FOREIGN KEY (`tb_sala_id_sala`)
    REFERENCES `fitness_life`.`tb_sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_pessoa` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_pessoa` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(15) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(15) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `rg` VARCHAR(20) NOT NULL,
  `telefone_residencial` VARCHAR(18) NOT NULL,
  `telefone_celular` VARCHAR(18) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_aluno` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_aluno` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `peso_inicial` FLOAT NULL DEFAULT NULL,
  `peso_durante` FLOAT NULL DEFAULT NULL,
  `data_entrada` DATE NOT NULL,
  `foto` BLOB NULL,
  PRIMARY KEY (`id_pessoa_cpf`),
  INDEX `fk_tb_aluno_tb_pessoa1_idx` (`id_pessoa_cpf` ASC) ,
  CONSTRAINT `fk_tb_aluno_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_funcionario` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_funcionario` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_pessoa_cpf`),
  INDEX `fk_tb_funcionario_tb_pessoa1_idx` (`id_pessoa_cpf` ASC) ,
  CONSTRAINT `fk_tb_funcionario_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`usuario` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`usuario` (
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  `usuario` VARCHAR(15) NULL DEFAULT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil_idperfil` INT(4) NOT NULL,
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC) ,
  PRIMARY KEY (`id_pessoa_cpf`),
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `fitness_life`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tb_pessoa1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_professor` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_professor` (
  `tb_funcionario_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`tb_funcionario_id_pessoa_cpf`),
  CONSTRAINT `fk_tb_professor_tb_funcionario1`
    FOREIGN KEY (`tb_funcionario_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_funcionario` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_auditoria_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_auditoria_pagamento` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_auditoria_pagamento` (
  `id` INT(11) NOT NULL,
  `data_log` TIMESTAMP NOT NULL,
  `coluna_alterada` VARCHAR(30) NOT NULL,
  `valor_antigo` VARCHAR(250) NOT NULL,
  `mysql_user` VARCHAR(50) NOT NULL,
  `tb_aluno_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_auditoria_pagamento_tb_aluno1_idx` (`tb_aluno_id_pessoa_cpf` ASC) ,
  CONSTRAINT `fk_tb_auditoria_pagamento_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_aluno` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_pagamento` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_pagamento` (
  `id_data_emissao` DATE NOT NULL,
  `tb_aluno_id_pessoa_cpf1` VARCHAR(11) NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `status` ENUM('Em aberto', 'Pago', 'Vencido') NOT NULL DEFAULT 'Em aberto',
  `boleto` LONGBLOB NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_data_emissao`, `tb_aluno_id_pessoa_cpf1`),
  INDEX `fk_tb_pagamento_tb_aluno1_idx` (`tb_aluno_id_pessoa_cpf1` ASC) ,
  CONSTRAINT `fk_tb_pagamento_tb_aluno1`
    FOREIGN KEY (`tb_aluno_id_pessoa_cpf1`)
    REFERENCES `fitness_life`.`tb_aluno` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_agendamento` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_agendamento` (
  `id_agenda_semanal` INT(4) NOT NULL,
  `id_pessoa_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_agenda_semanal`, `id_pessoa_cpf`),
  INDEX `fk_tb_agenda_semanal_has_tb_aluno_tb_aluno1_idx` (`id_pessoa_cpf` ASC) ,
  INDEX `fk_tb_agenda_semanal_has_tb_aluno_tb_agenda_semanal1_idx` (`id_agenda_semanal` ASC) ,
  CONSTRAINT `fk_tb_agenda_semanal_has_tb_aluno_tb_agenda_semanal1`
    FOREIGN KEY (`id_agenda_semanal`)
    REFERENCES `fitness_life`.`tb_agenda_semanal` (`id_agenda_semanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agenda_semanal_has_tb_aluno_tb_aluno1`
    FOREIGN KEY (`id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_aluno` (`id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `fitness_life`.`tb_agenda_semanal_has_tb_professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fitness_life`.`tb_agenda_semanal_has_tb_professor` ;

CREATE TABLE IF NOT EXISTS `fitness_life`.`tb_agenda_semanal_has_tb_professor` (
  `tb_agenda_semanal_id_agenda_semanal` INT(4) NOT NULL,
  `tb_professor_tb_funcionario_id_pessoa_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`tb_agenda_semanal_id_agenda_semanal`, `tb_professor_tb_funcionario_id_pessoa_cpf`),
  INDEX `fk_tb_agenda_semanal_has_tb_professor_tb_professor1_idx` (`tb_professor_tb_funcionario_id_pessoa_cpf` ASC) ,
  INDEX `fk_tb_agenda_semanal_has_tb_professor_tb_agenda_semanal1_idx` (`tb_agenda_semanal_id_agenda_semanal` ASC) ,
  CONSTRAINT `fk_tb_agenda_semanal_has_tb_professor_tb_agenda_semanal1`
    FOREIGN KEY (`tb_agenda_semanal_id_agenda_semanal`)
    REFERENCES `fitness_life`.`tb_agenda_semanal` (`id_agenda_semanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_agenda_semanal_has_tb_professor_tb_professor1`
    FOREIGN KEY (`tb_professor_tb_funcionario_id_pessoa_cpf`)
    REFERENCES `fitness_life`.`tb_professor` (`tb_funcionario_id_pessoa_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
